substitutions:
  #Name your Gateway
  device_name: carletz-zigbee
  #Home Assistant Name
  friendly_name: Carletz Gateway

esphome:
  name: "${device_name}"

esp32:
  board: esp32dev
  framework:
    type: esp-idf #arduino

#Ethernet connection information
ethernet:
  type:  LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  manual_ip:
    static_ip: 192.168.1.XXX      # change for your use
    gateway: 192.168.1.1
    subnet: 255.255.255.0

ota:
  - platform: esphome
    password: ""

## General ESPHome settings
# Logger is enabled
logger:
  level: DEBUG

# Enable WEB
web_server:
  port: 80
  version: 3
  
# Enable HA Time
time:
  - platform: sntp
    id: sntp_time
#   - platform: homeassistant
#     id: homeassistant_time

#External component Stream Server
external_components:
  - source: github://mercenaruss/esphome-stream-server

# Extra sensor to keep track of gateway uptime
text_sensor:
  - platform: template
    name: "${friendly_name} Uptime"
    lambda: |-
      uint32_t dur = id(uptime_s).state;
      int dys = 0;
      int hrs = 0;
      int mnts = 0;
      if (dur > 86399) {
        dys = trunc(dur / 86400);
        dur = dur - (dys * 86400);
      }
      if (dur > 3599) {
        hrs = trunc(dur / 3600);
        dur = dur - (hrs * 3600);
      }
      if (dur > 59) {
        mnts = trunc(dur / 60);
        dur = dur - (mnts * 60);
      }
      char buffer[17];
      sprintf(buffer, "%ud %02uh %02um %02us", dys, hrs, mnts, dur);
      return {buffer};
    update_interval: 60s

#Uptime
sensor:
  - platform: uptime
    id: uptime_s
    update_interval: 60s

# Device functions:
switch:
  - platform: restart
    name: "Gateway Restart"

  - platform: gpio
    pin: 33
    id: zRST_gpio
    inverted: yes
    restore_mode: ALWAYS_OFF
  - platform: template
    name: "Zigbee RST"
    id: zRST
    turn_on_action:
      - switch.turn_on: zRST_gpio
      - delay: 15ms
      - switch.turn_off: zRST_gpio
      
  - platform: gpio
    pin: 32
    name: "Zigbee BSL"
    id: zBSL
    inverted: yes
    restore_mode: ALWAYS_OFF
    internal: true
    
  - platform: template
    name: "Firmware Update"
    turn_on_action:
      - script.execute: fw_update_mode
    turn_off_action:
      - switch.toggle: zRST

# Update CC2652 Firmware
script:
  - id: fw_update_mode
    then:
      - switch.turn_on: zBSL
      - delay: 1s
      - switch.turn_on: zRST_gpio
      - delay: 1s
      - switch.turn_off: zRST_gpio
      - logger.log: "Delaying ~5 seconds for TI chip to be ready"
      - delay: 5s
      - switch.turn_off: zBSL
      - logger.log: "Update with cc2538-bsl tool now!"
      - logger.log: "Usage: cc2538_bsl.py -p socket://192.168.1.8:6638 -evw CC1352P2_CC2652P_launchpad_coordinator_20250321.hex"

#UART Settings
uart:
  id: uart_bus
  rx_pin: GPIO16
  tx_pin: GPIO13
  baud_rate: 115200

#Serial Bridge Settings,uncomment #port to change default 6638 TCP port
stream_server:
  uart_id: uart_bus
#  port: 1234